name: animated_responsive_layout
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
    - avatar_1.png
    - avatar_2.png
    - avatar_3.png
    - avatar_4.png
    - avatar_5.png
    - avatar_6.png
    - avatar_7.png
    - thumbnail_1.png
